site_name: OpenAVMKit
site_description: Free and open source AVM (Automated Valuation Model) for real estate mass appraisal
repo_url: https://github.com/larsiusprime/openavmkit

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [openavmkit]
          options:
            docstring_style: numpy
            merge_init_into_class: true
            separate_signature: true
  - gen-files:
      scripts:
        - docs/reference/gen.py
  - literate-nav

nav:
  - Home: index.md
  - API: reference/
