name: Run Pytest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check dependency conflicts
        run: |
          pip install pipdeptree
          pipdeptree --warn fail

      - name: Run tests
        run: python -m pytest tests/ --junitxml=report.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml
